CREATE TABLE BOTTLE(
  BOTTLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BOTTLE_QUANTITY VARCHAR(10) NOT NULL,
  BOTTLE_BRAND VARCHAR(64) NOT NULL,
  BOTTLE_PRICE INT NOT NULL,
  BOTTLE_IMG VARCHAR(220) NOT NULL
);

CREATE TABLE BUYER(
  BUYER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24)
);

CREATE TABLE ORDERS(
  ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BOTTLE_ID BIGINT NOT NULL,
  BUYER_ID BIGINT NOT NULL,
  ORDER_DATE DATE,
  ORDER_QUANTITY INT NOT NULL,
  DELIVERED INT NOT NULL
);

ALTER TABLE ORDERS ADD FOREIGN KEY (BOTTLE_ID) REFERENCES BOTTLE(BOTTLE_ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (BUYER_ID) REFERENCES BUYER(BUYER_ID);
CREATE INDEX IDX_ORD_DATE_ ON ORDERS(ORDER_DATE);
